__version__ = "0.1.1"
__copyright__ = "Copyright (c) 2020-2023 The PyUnity Team"
__email__ = "tankimarshal2@gmail.com"
__license__ = "MIT License"
__summary__ = "An Editor for PyUnity in the style of the UnityEditor"
__title__ = "pyunity-editor"
__uri__ = "https://github.com/pyunity/pyunity-gui"
