name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8.10", "3.9.13", "3.10.11"]
        architecture: ["x64", "x86"]
    name: Python ${{ matrix.python-version }}-${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies
        run: pip install wheel build
      - uses: ilammy/msvc-dev-cmd@v1
        name: Set up MSVC
      - name: Build application
        env:
          GITHUB_ACTIONS: 1
          PYTHON_VERSION: ${{ matrix.python-version }}
          PYTHON_ARCHITECTURE: ${{ matrix.architecture }}
        run: python builder.py
      - name: Upload zip artifact
        uses: actions/upload-artifact@v3
        with:
          name: Zip archive (${{ matrix.python-version }}-${{ matrix.architecture }})
          path: pyunity-editor.zip
      - name: Upload 7z artifact
        uses: actions/upload-artifact@v3
        with:
          name: 7z archive (${{ matrix.python-version }}-${{ matrix.architecture }})
          path: pyunity-editor.7z
      - name: Upload self-extracting artifact
        uses: actions/upload-artifact@v3
        with:
          name: Self-extracting archive (${{ matrix.python-version }}-${{ matrix.architecture }})
          path: pyunity-editor-install.exe
